apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: example-namespace
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
