apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: example-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/ethereal-smoke-422723-i0/my-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PGHOST
              value: "34.133.181.58"
            - name: PGDATABASE
              value: "postgres"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "Kunal"
